CREATE DATABASE IF NOT EXISTS `LOGIN` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `LOGIN`;

CREATE TABLE IF NOT EXISTS `users`(
 `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 `username` VARCHAR(50) NOT NULL UNIQUE,
 `password` VARCHAR(255) NOT NULL,
 `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=latin1;